apiVersion: v1
kind: Service
metadata:
  name: mssql # Sets service name
  labels:
    app: mssql # Labels and Selectors
spec:
  type: ClusterIP # Sets service type
  ports:
    - port: 1433 # Sets port to run the postgres application
      targetPort: 1433
  selector:
    app: mssql