apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest # Sets Image
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 1433 # Exposes container port
          envFrom:
            - configMapRef:
                name: mssql-config
          env:
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: password
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: mssqldb
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: mssql-pv-claim
