kind: PersistentVolume
apiVersion: v1
metadata:
  name: mssql-pv-volume  # Sets PV's name
  labels:
    type: local  # Sets PV's type to local
    app: mssql
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/mssqldata"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-pv-claim  # Sets name of PVC
  labels:
    app: mssql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: 2Gi  # Sets volume size