version: "3"
services:
  sqldb:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    volumes:
      - ./config/:/mosquitto/config/:ro
      - ./log/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
  redis:
    container_name: cryosdonorqueue-redis
    image: redis:6.2-alpine
    hostname: redis
    ports:
      - '6379:6379'
volumes:
  db_data: ~
